name: Build and Push Containers

on:
  push:
    branches:
      - main  # Adjust if you use a different branch as your default

jobs:
  build-apptainer:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install Apptainer
      run: |
        wget https://github.com/apptainer/apptainer/releases/download/v1.0.1/apptainer_1.0.1_amd64.deb
        sudo dpkg -i apptainer_1.0.1_amd64.deb

    - name: Build Apptainer image
      run: apptainer build treemort.sif env/treemort/conda_environment.def

    - name: Push to Quay.io (Apptainer)
      run: echo "PUSH COMMAND HERE"  # You'll need to replace this with the command to push the sif file to Quay.io

  build-and-push-docker:
    runs-on: ubuntu-latest
    needs: build-apptainer
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Log in to quay.io
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./env/treemort
        file: ./env/treemort/Dockerfile
        push: true
        tags: quay.io/your-username/treemort:latest  # Replace `your-username` with your actual Quay.io username
